workflows:
  ios:
    scripts:
      - name: "Build iOS"
        script: |
          xcodebuild archive \
          -scheme "WhatFlower" \
          -archivePath archive.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          cd archive.xcarchive/Products/Applications/
          mkdir Payload
          mv WhatFlower.app Payload
          zip -r Payload.zip Payload
          mv Payload.zip WhatFlower.ipa
    artifacts:
      - /Users/builder/clone/archive.xcarchive/Products/Applications/*.ipa
    publishing:
      email:
        recipients:
          - amourakora2001@gmail.com
    triggering:
      events:
        - push